### ISSUE TITLE
Regarding Implementation of trimIndent

### ISSUE THREAD

**Issue by Dutta-SD** [insolor/python-trim#2]
Hi, I came across this repository and read the docs. 

From what I understand of the `trimIndent` function in Kotlin, is this a possible solution? 
```python
s = """
            ABC
            123
            456
"""
def trimIndent(s : str):
    return s.strip().replace(' ', '')

trimIndent(s) #ABC\n123\n456
```
If this is what is needed, can I open a pull request regarding the same?

**Comment by insolor** [comment]
@Dutta-SD Hi, you are fast I've just created the repo less than an hour ago :)

As for your implementation, it will remove spaces inside a string, e.g. "A B C" will become "ABC".

Also, it mustn't just remove leading spaces, it must remove maximum common indentation, so that:
```
"""
    ABC
     123
      456
"""
```
must be converted to
```
"""
ABC
 123
  456
"""
```

**Comment by insolor** [comment]
I'm going to use some ideas from the Kolin source code of [trimIndent](https://github.com/JetBrains/kotlin/blob/80cce1dc5280eb9135390270c8644a7b8d198071/libraries/stdlib/src/kotlin/text/Indent.kt#L63), but I think I won't make an exact copy of the implementation.

**Comment by insolor** [comment]
Anyways, if you have any suggestions, feel free to share. Also, I think I'll convert this issue to a discussion.
